-- SportBook - Esquema complet, dades inicials, RLS i funcions de domini.
-- Codi executable dins un projecte Supabase nou.

begin;

create extension if not exists btree_gist;

create table public.courts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  sport_type text not null check (sport_type in ('padel', 'tennis', 'futbol_sala', 'basquet', 'natacio', 'squash')),
  description text,
  capacity integer not null check (capacity > 0 and capacity <= 30),
  price_per_hour numeric(6, 2) not null check (price_per_hour >= 0),
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text check (full_name is null or char_length(full_name) between 2 and 100),
  email text,
  created_at timestamptz not null default now()
);

create table public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  court_id bigint not null references public.courts(id) on delete restrict,
  booking_date date not null,
  start_time time not null,
  end_time time not null,
  status text not null default 'active' check (status in ('active', 'cancelled')),
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  constraint bookings_valid_time_range check (end_time > start_time),
  constraint bookings_one_hour check (end_time - start_time = interval '1 hour'),
  constraint bookings_opening_hours check (start_time >= time '08:00' and end_time <= time '22:00'),
  constraint bookings_full_hour check (
    extract(minute from start_time) = 0 and extract(second from start_time) = 0 and
    extract(minute from end_time) = 0 and extract(second from end_time) = 0
  ),
  constraint bookings_cancelled_consistency check (
    (status = 'active' and cancelled_at is null) or
    (status = 'cancelled' and cancelled_at is not null)
  )
);

-- Protecció atòmica contra dobles reserves, també davant peticions simultànies.
alter table public.bookings
  add constraint bookings_no_overlap
  exclude using gist (
    court_id with =,
    (tsrange(booking_date + start_time, booking_date + end_time, '[)')) with &&
  ) where (status = 'active');

create index bookings_user_date_idx on public.bookings (user_id, booking_date desc, start_time desc);
create index bookings_court_date_idx on public.bookings (court_id, booking_date, start_time)
  where status = 'active';
create index courts_sport_type_idx on public.courts (sport_type, name);

insert into public.courts (name, sport_type, description, capacity, price_per_hour) values
  ('Pàdel 1', 'padel', 'Pista coberta amb il·luminació LED i gespa d’última generació.', 4, 12.00),
  ('Pàdel 2', 'padel', 'Pista exterior amb paret de vidre panoràmica.', 4, 10.00),
  ('Pàdel 3', 'padel', 'Pista central coberta preparada per a competició.', 4, 14.00),
  ('Pàdel 4', 'padel', 'Pista exterior il·luminada.', 4, 10.00),
  ('Tennis 1', 'tennis', 'Pista de terra batuda amb reg automàtic.', 4, 15.00),
  ('Tennis 2', 'tennis', 'Pista ràpida de ciment.', 4, 15.00),
  ('Futbol sala A', 'futbol_sala', 'Pista coberta amb marcador electrònic.', 10, 30.00),
  ('Futbol sala B', 'futbol_sala', 'Pista amb gespa artificial i graderia.', 14, 35.00),
  ('Bàsquet 1', 'basquet', 'Pista exterior amb dues cistelles regulables.', 10, 20.00),
  ('Bàsquet 2', 'basquet', 'Pista coberta amb parquet.', 10, 24.00),
  ('Piscina - Carrer 1', 'natacio', 'Carrer de piscina semiolímpica de 25 metres.', 2, 6.00),
  ('Esquaix 1', 'squash', 'Pista interior climatitzada.', 2, 8.00);

-- Perfil automàtic després del registre.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (new.id, nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Disponibilitat pública i anonimitzada: mai exposa user_id ni altres dades personals.
create or replace function public.get_court_availability(
  p_court_id bigint,
  p_date date
)
returns table (booking_date date, start_time time, end_time time)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select b.booking_date, b.start_time, b.end_time
  from public.bookings b
  where b.court_id = p_court_id
    and b.booking_date = p_date
    and b.status = 'active'
  order by b.start_time;
$$;

-- Creació centralitzada: valida les regles i deixa la concurrència a PostgreSQL.
create or replace function public.create_booking(
  p_court_id bigint,
  p_booking_date date,
  p_start_time time,
  p_end_time time
)
returns public.bookings
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_booking public.bookings;
begin
  if v_user_id is null then
    raise exception 'Has d’iniciar sessió.' using errcode = 'P0001';
  end if;

  if not exists (select 1 from public.courts where id = p_court_id) then
    raise exception 'La pista indicada no existeix.' using errcode = 'P0001';
  end if;

  if p_booking_date < current_date or p_booking_date > current_date + 60 then
    raise exception 'La data ha d’estar entre avui i els pròxims 60 dies.' using errcode = 'P0001';
  end if;

  if p_start_time < time '08:00' or p_end_time > time '22:00' or
     p_end_time - p_start_time <> interval '1 hour' or
     extract(minute from p_start_time) <> 0 or extract(second from p_start_time) <> 0 then
    raise exception 'La franja horària no és vàlida.' using errcode = 'P0001';
  end if;

  if p_booking_date + p_start_time <= (current_timestamp at time zone 'Europe/Madrid') then
    raise exception 'No es pot reservar una franja que ja ha començat.' using errcode = 'P0001';
  end if;

  insert into public.bookings (user_id, court_id, booking_date, start_time, end_time)
  values (v_user_id, p_court_id, p_booking_date, p_start_time, p_end_time)
  returning * into v_booking;

  return v_booking;
exception
  when exclusion_violation then
    raise exception 'La franja seleccionada se solapa amb una reserva existent.' using errcode = '23P01';
end;
$$;

-- Cancel·lació lògica: conserva l’historial i allibera la franja.
create or replace function public.cancel_booking(p_booking_id bigint)
returns public.bookings
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_booking public.bookings;
begin
  if v_user_id is null then
    raise exception 'Has d’iniciar sessió.' using errcode = 'P0001';
  end if;

  select * into v_booking
  from public.bookings
  where id = p_booking_id and user_id = v_user_id;

  if not found then
    raise exception 'Reserva no trobada.' using errcode = 'P0001';
  end if;

  if v_booking.status = 'cancelled' then
    raise exception 'La reserva ja està cancel·lada.' using errcode = 'P0001';
  end if;

  if v_booking.booking_date + v_booking.start_time <= (current_timestamp at time zone 'Europe/Madrid') then
    raise exception 'No es pot cancel·lar una reserva que ja ha començat.' using errcode = 'P0001';
  end if;

  update public.bookings
  set status = 'cancelled', cancelled_at = now()
  where id = p_booking_id
  returning * into v_booking;

  return v_booking;
end;
$$;

alter table public.courts enable row level security;
alter table public.profiles enable row level security;
alter table public.bookings enable row level security;

create policy courts_select_public on public.courts
for select to anon, authenticated using (true);

create policy profiles_select_own on public.profiles
for select to authenticated using ((select auth.uid()) = id);

create policy profiles_update_own on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy bookings_select_own on public.bookings
for select to authenticated using ((select auth.uid()) = user_id);

-- Permisos mínims. Les escriptures de reserves només passen per les funcions anteriors.
revoke all on public.courts from anon, authenticated;
revoke all on public.profiles from anon, authenticated;
revoke all on public.bookings from anon, authenticated;

grant select on public.courts to anon, authenticated;
grant select on public.profiles to authenticated;
grant update (full_name) on public.profiles to authenticated;
grant select on public.bookings to authenticated;

revoke execute on function public.get_court_availability(bigint, date) from public;
revoke execute on function public.create_booking(bigint, date, time, time) from public, anon;
revoke execute on function public.cancel_booking(bigint) from public, anon;
grant execute on function public.get_court_availability(bigint, date) to anon, authenticated;
grant execute on function public.create_booking(bigint, date, time, time) to authenticated;
grant execute on function public.cancel_booking(bigint) to authenticated;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

commit;
